#!/usr/bin/env python3
"""Inspect built archives without extracting them. Never print matched secrets.

This complements tracked-source scans: build tools can include untracked files.
Structural patterns are not a substitute for semantic/privacy history review.
"""
import argparse
import gzip
import pathlib
import re
import stat
import tarfile
import tomllib
import zipfile

from privacy_scan import PATTERNS, load_extra

ROOT = pathlib.Path(__file__).resolve().parents[1]
MAX_MEMBER_BYTES = 16 * 1024 * 1024
MAX_ARCHIVE_BYTES = 64 * 1024 * 1024
MAX_MEMBERS = 10000


def check_artifact(path):
    path = pathlib.Path(path)
    try:
        config = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
        targets = config["tool"]["hatch"]["build"]["targets"]
        roots = targets["sdist"]["only-include"]
        if not isinstance(roots, list) or not roots or not all(isinstance(p, str) for p in roots):
            return [(0, "missing or invalid sdist allow-list")]
        allowed = set(roots)
        wheel_roots = {pathlib.PurePosixPath(p).name for p in targets["wheel"]["packages"]}
        project = config["project"]
        dist_name = re.sub(r"[-_.]+", "_", project["name"])
        wheel_roots.add(f"{dist_name}-{project['version']}.dist-info")
    except (OSError, ValueError, KeyError, TypeError):
        return [(0, "missing or invalid distribution allow-list")]
    allowed.add("PKG-INFO")  # Generated by the build backend, not a source file.
    checks = [(re.compile(pattern), label) for pattern, label in PATTERNS + load_extra()]
    findings = []
    files = 0
    entries = 0
    payload_bytes = 0

    def scan(value, index):
        text = value.decode("utf-8", errors="replace") if isinstance(value, bytes) else str(value)
        for pattern, label in checks:
            if pattern.search(text):
                findings.append((index, label))

    def header(name, size, directory, regular, source=False):
        nonlocal entries
        entries += 1
        scan(name, entries)
        if entries > MAX_MEMBERS:
            findings.append((entries, "too many archive members"))
            return False
        # Permit one conventional directory terminator, not empty path segments.
        normalized = name[:-1] if directory and name.endswith("/") else name
        parts = normalized.split("/")
        if (normalized.startswith("/") or "\\" in normalized
                or re.match(r"^[A-Za-z]:", normalized)
                or any(p in ("", ".", "..") for p in parts)
                or any(ord(c) < 32 for c in name)):
            findings.append((entries, "unsafe member path"))
            return False
        if any(p in (".git", ".hg", ".svn", ".venv", "__pycache__") for p in parts):
            findings.append((entries, "private build/VCS member"))
            return False
        source_root = source and directory and len(parts) == 1
        if source and not source_root and (len(parts) < 2 or parts[1] not in allowed):
            findings.append((entries, "member outside sdist allow-list"))
            return False
        if not source and parts[0] not in wheel_roots:
            findings.append((entries, "member outside wheel allow-list"))
            return False
        if not regular and not directory:
            findings.append((entries, "unsupported archive member type"))
            return False
        if size < 0 or size > MAX_MEMBER_BYTES:
            findings.append((entries, "member exceeds inspection bound"))
            return False
        if directory and size:
            findings.append((entries, "directory carries a payload"))
            return False
        return True

    def payload(handle):
        nonlocal files, payload_bytes
        data = handle.read(MAX_MEMBER_BYTES + 1)
        payload_bytes += len(data)
        if len(data) > MAX_MEMBER_BYTES or payload_bytes > MAX_ARCHIVE_BYTES:
            findings.append((entries, "payload exceeds inspection bound"))
            return
        files += 1
        scan(data, entries)

    try:
        # Scan raw envelopes as well as parsed fields. This covers ZIP local
        # extras/comments and TAR PAX records a parser may override or consume.
        with path.open("rb") as handle:
            raw = handle.read(MAX_ARCHIVE_BYTES + 1)
        if len(raw) > MAX_ARCHIVE_BYTES:
            return [(0, "artifact exceeds inspection bound")]
        scan(raw, 0)
        if path.suffix == ".whl":
            with zipfile.ZipFile(path) as archive:
                scan(archive.comment, 0)
                for member in archive.infolist():
                    mode = stat.S_IFMT(member.external_attr >> 16)
                    directory = member.is_dir() and mode in (0, stat.S_IFDIR)
                    regular = not member.is_dir() and mode in (0, stat.S_IFREG)
                    valid = header(member.orig_filename, member.file_size, directory, regular)
                    scan(member.comment, entries)
                    scan(member.extra, entries)
                    if entries > MAX_MEMBERS or payload_bytes > MAX_ARCHIVE_BYTES:
                        break
                    if not valid:
                        continue
                    # Open even directories: zipfile checks the local filename
                    # against the central directory and verifies the payload.
                    with archive.open(member) as handle:
                        if directory:
                            if handle.read(1):
                                findings.append((entries, "directory carries a payload"))
                        else:
                            payload(handle)
        elif path.name.endswith(".tar.gz"):
            with gzip.open(path, "rb") as handle:
                raw_tar = handle.read(MAX_ARCHIVE_BYTES + 1)
            if len(raw_tar) > MAX_ARCHIVE_BYTES:
                return findings + [(0, "expanded archive exceeds inspection bound")]
            scan(raw_tar, 0)
            with tarfile.open(path, "r:gz") as archive:
                for member in archive:
                    valid = header(member.name, member.size, member.isdir(), member.isfile(), source=True)
                    # No type, including a directory, bypasses metadata checks.
                    scan(repr(member.pax_headers), entries)
                    scan(member.uname, entries)
                    scan(member.gname, entries)
                    scan(member.linkname, entries)
                    if entries > MAX_MEMBERS or payload_bytes > MAX_ARCHIVE_BYTES:
                        break
                    if valid and member.isfile():
                        with archive.extractfile(member) as handle:
                            payload(handle)
                scan(repr(archive.pax_headers), 0)
        else:
            return [(0, "unsupported artifact format")]
    except (OSError, EOFError, ValueError, tarfile.TarError, zipfile.BadZipFile, RuntimeError):
        return findings + [(0, "artifact unreadable or malformed")]
    if not files:
        findings.append((0, "empty artifact"))
    return findings


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("artifacts", nargs="+")
    args = parser.parse_args(argv)
    failed = False
    for index, path in enumerate(args.artifacts, 1):
        findings = check_artifact(path)
        for member, label in findings:
            # Neither payloads nor untrusted member names belong in CI logs.
            print(f"artifact {index}, member {member}: {label}")
        failed |= bool(findings)
    print("distribution check: FAILED" if failed else "distribution check: clean")
    return int(failed)


if __name__ == "__main__":
    raise SystemExit(main())
