#!/usr/bin/env python3
"""Inspect built archives without extracting them. Never print matched secrets.

This complements tracked-source scans: build tools can include untracked files.
Structural patterns are not a substitute for semantic/privacy history review.
"""
import argparse
import pathlib
import re
import stat
import tarfile
import tomllib
import zipfile

from privacy_scan import PATTERNS, load_extra

ROOT = pathlib.Path(__file__).resolve().parents[1]
MAX_MEMBER_BYTES = 16 * 1024 * 1024


def check_artifact(path):
    path = pathlib.Path(path)
    try:
        config = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
        roots = config["tool"]["hatch"]["build"]["targets"]["sdist"]["only-include"]
        if not isinstance(roots, list) or not roots or not all(isinstance(p, str) for p in roots):
            return [(0, "missing or invalid sdist allow-list")]
        allowed = set(roots)
    except (OSError, ValueError, KeyError, TypeError):
        return [(0, "missing or invalid sdist allow-list")]
    allowed.add("PKG-INFO")  # Generated by the build backend, not a source file.
    checks = [(re.compile(pattern), label) for pattern, label in PATTERNS + load_extra()]
    findings = []
    files = 0

    def inspect(name, size, read, regular=True, source=False):
        nonlocal files
        files += 1
        parts = name.split("/")
        if (name.startswith("/") or "\\" in name or any(p in ("", ".", "..") for p in parts)
                or any(ord(c) < 32 for c in name)):
            findings.append((files, "unsafe member path"))
            return
        if any(p in (".git", ".hg", ".svn", ".venv", "__pycache__") for p in parts):
            findings.append((files, "private build/VCS member"))
            return
        if source and (len(parts) < 2 or parts[1] not in allowed):
            findings.append((files, "member outside sdist allow-list"))
            return
        if not regular:
            findings.append((files, "non-regular archive member"))
            return
        if size > MAX_MEMBER_BYTES:
            findings.append((files, "member exceeds inspection bound"))
            return
        data = read(MAX_MEMBER_BYTES + 1)
        if len(data) > MAX_MEMBER_BYTES:
            findings.append((files, "member exceeds inspection bound"))
            return
        text = name + "\n" + data.decode("utf-8", errors="replace")
        for pattern, label in checks:
            if pattern.search(text):
                findings.append((files, label))

    try:
        if path.suffix == ".whl":
            with zipfile.ZipFile(path) as archive:
                for member in archive.infolist():
                    if member.is_dir():
                        if ".git" in member.filename.split("/"):
                            findings.append((files, "private build/VCS directory"))
                        continue
                    with archive.open(member) as handle:
                        inspect(member.filename, member.file_size, handle.read,
                                regular=not stat.S_ISLNK(member.external_attr >> 16))
        elif path.name.endswith(".tar.gz"):
            with tarfile.open(path, "r:gz") as archive:
                for member in archive:
                    if member.isdir():
                        if ".git" in member.name.split("/"):
                            findings.append((files, "private build/VCS directory"))
                        continue
                    if not member.isfile():
                        inspect(member.name, member.size, lambda n: b"", regular=False, source=True)
                        continue
                    with archive.extractfile(member) as handle:
                        inspect(member.name, member.size, handle.read, source=True)
                    # Paths/secrets can also hide in tar metadata, not just files.
                    metadata = repr(member.pax_headers) + member.uname + member.gname
                    for pattern, label in checks:
                        if pattern.search(metadata):
                            findings.append((files, label))
        else:
            return [(0, "unsupported artifact format")]
    except (OSError, EOFError, ValueError, tarfile.TarError, zipfile.BadZipFile, RuntimeError):
        return findings + [(0, "artifact unreadable or malformed")]
    if not files:
        findings.append((0, "empty artifact"))
    return findings


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("artifacts", nargs="+")
    args = parser.parse_args(argv)
    failed = False
    for index, path in enumerate(args.artifacts, 1):
        findings = check_artifact(path)
        for member, label in findings:
            # Neither payloads nor untrusted member names belong in CI logs.
            print(f"artifact {index}, member {member}: {label}")
        failed |= bool(findings)
    print("distribution check: FAILED" if failed else "distribution check: clean")
    return int(failed)


if __name__ == "__main__":
    raise SystemExit(main())
